FROM node:12.14.0-alpine3.11 as frontend

WORKDIR /home/node/app

COPY --chown=node frontend .

RUN npm install 

RUN npm run build

FROM codeeducation/keycloak:11.0.2-fix-translate

COPY --from=frontend /home/node/app/build/. /opt/jboss/keycloak/themes